Attribute VB_Name = "Specs"
Option Explicit

Public Sub SetupTreeView()

 'Constants
 frmMain.TV.Nodes.Add , , "Constants", "Constants"
 frmMain.TV.Nodes.Add "Constants", tvwChild, "C0", "Constant Registers"
 frmMain.TV.Nodes.Add "C0", tvwChild, "CREX", "To define cX registers put - def c0, Red(-1 - 1), Green(-1 - 1), Blue(-1 - 1), Alpha(-1 - 1)"
 frmMain.TV.Nodes.Add "C0", tvwChild, "CREX2", "Example - def c0, 0.11, 0.75, -0.5, 0.2"
 frmMain.TV.Nodes.Add "C0", tvwChild, "CR1", "c0"
 frmMain.TV.Nodes.Add "C0", tvwChild, "CR2", "c1"
 frmMain.TV.Nodes.Add "C0", tvwChild, "CR3", "c2"
 frmMain.TV.Nodes.Add "C0", tvwChild, "CR4", "c3"
 frmMain.TV.Nodes.Add "C0", tvwChild, "CR5", "c4"
 frmMain.TV.Nodes.Add "C0", tvwChild, "CR6", "c5"
 frmMain.TV.Nodes.Add "C0", tvwChild, "CR7", "c6"
 frmMain.TV.Nodes.Add "C0", tvwChild, "CR8", "c7"
 frmMain.TV.Nodes.Add "Constants", tvwChild, "C1", "Texture Registers"
 frmMain.TV.Nodes.Add "C1", tvwChild, "TR1", "t0"
 frmMain.TV.Nodes.Add "C1", tvwChild, "TR2", "t1"
 frmMain.TV.Nodes.Add "C1", tvwChild, "TR3", "t2"
 frmMain.TV.Nodes.Add "C1", tvwChild, "TR4", "t3"
 frmMain.TV.Nodes.Add "C1", tvwChild, "TR5", "t4"
 frmMain.TV.Nodes.Add "C1", tvwChild, "TR6", "t5"
 frmMain.TV.Nodes.Add "C1", tvwChild, "TR7", "t6"
 frmMain.TV.Nodes.Add "C1", tvwChild, "TR8", "t7"
 frmMain.TV.Nodes.Add "Constants", tvwChild, "C2", "Temporary Registers"
 frmMain.TV.Nodes.Add "C2", tvwChild, "TMPREX", "Note: May go up to r8"
 frmMain.TV.Nodes.Add "C2", tvwChild, "TMPR1", "r0"
 frmMain.TV.Nodes.Add "C2", tvwChild, "TMPR2", "r1"
 frmMain.TV.Nodes.Add "Constants", tvwChild, "C3", "Color Registers"
 frmMain.TV.Nodes.Add "C3", tvwChild, "CLRR1", "v0"
 frmMain.TV.Nodes.Add "C3", tvwChild, "CLRR2", "v1"
 DoEvents
 
 'Texture Address Instructions
 frmMain.TV.Nodes.Add , , "Texture_Address", "Texture Address Instructions"
 frmMain.TV.Nodes.Add "Texture_Address", tvwChild, "TA1_1", "PS Version 1.1"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA111EX1", "d = Destination"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA111EX2", "s = Source"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA111", "tex (d)                                  Example - tex t0"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA112", "texbem (d, s)                            Example - texbem t1, t0"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA113", "texbeml (d, s)                           Example - texbeml t1, t0"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA114", "texcoord (d)                             Example - texcoord t0"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA115", "texkill (s)                              Example - texkill t0"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA116", "texm3x2pad (d, s)                        Example - texm3x2pad r0, t1"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA117", "texm3x2tex (d, s)                        Example - texm3x2tex t1, t0"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA118", "texm3x3pad (d, s)                        Example - texm3x3pad r0, t1"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA119", "texm3x3spec (d, s1, s2)                  Example - texm3x3spec r0, t0, t1"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA1110", "texm3x3tex (d, s)                        Example - texm3x3tex t1, t0"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA1111", "texm3x3vspec (d, s)                      Example - texm3x3vspec t1, t0"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA1112", "texreg2ar (d, s)                         Example - texreg2ar r0, t1"
 frmMain.TV.Nodes.Add "TA1_1", tvwChild, "TA1113", "texreg2gb (d, s)                         Example - texreg2gb r0, t1"
 
 frmMain.TV.Nodes.Add "Texture_Address", tvwChild, "TA1_2", "PS Version 1.2"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA121EX1", "d = Destination"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA121EX2", "s = Source"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA121", "tex (d)                                  Example - tex t0"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA122", "texbem (d, s)                            Example - texbem t1, t0"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA123", "texbeml (d, s)                           Example - texbeml t1, t0"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA124", "texcoord (d)                             Example - texcoord t0"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA125", "texdp3 (d, s)                            Example - texdp3 t1, t0"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA126", "texdp3tex (d, s)                         Example - texdp3tex t1, t0"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA127", "texkill (s)                              Example - texkill t0"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA128", "texm3x2pad (d, s)                        Example - texm3x2pad r0, t1"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA129", "texm3x2tex (d, s)                        Example - texm3x2tex t1, t0"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA1210", "texm3x3 (d, s)                           Example - texm3x3 t1, t0"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA1211", "texm3x3pad (d, s)                        Example - texm3x3pad r0, t1"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA1212", "texm3x3spec (d, s1, s2)                  Example - texm3x3spec r0, t0, t1"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA1213", "texm3x3tex (d, s)                        Example - texm3x3tex t1, t0"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA1214", "texm3x3vspec (d, s)                      Example - texm3x3vspec t1, t0"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA1215", "texreg2ar (d, s)                         Example - texreg2ar r0, t1"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA1216", "texreg2gb (d, s)                         Example - texreg2gb r0, t1"
 frmMain.TV.Nodes.Add "TA1_2", tvwChild, "TA1217", "texreg2rgb (d, s)                        Example - texreg2rgb r0, t1"
 
 frmMain.TV.Nodes.Add "Texture_Address", tvwChild, "TA1_3", "PS Version 1.3"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA131EX1", "d = Destination"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA131EX2", "s = Source"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA131", "tex (d)                                  Example - tex t0"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA132", "texbem (d, s)                            Example - texbem t1, t0"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA133", "texbeml (d, s)                           Example - texbeml t1, t0"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA134", "texcoord (d)                             Example - texcoord t0"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA135", "texdp3 (d, s)                            Example - texdp3 t1, t0"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA136", "texdp3tex (d, s)                         Example - texdp3tex t1, t0"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA137", "texkill (s)                              Example - texdp3tex t1, t0"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA138", "texm3x2depth (d, s)                      Example - texm3x2depth r0, t1"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA139", "texm3x2pad (d, s)                        Example - texm3x2pad r0, t1"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA1310", "texm3x2tex (d, s)                        Example - texm3x2tex t1, t0"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA1311", "texm3x3 (d, s)                           Example - texm3x3 t1, t0"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA1312", "texm3x3pad (d, s)                        Example - texm3x3pad r0, t1"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA1313", "texm3x3spec (d, s1, s2)                  Example - texm3x3spec r0, t0, t1"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA1314", "texm3x3tex (d, s)                        Example - texm3x3tex t1, t0"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA1315", "texm3x3vspec (d, s)                      Example - texm3x3vspec t1, t0"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA1316", "texreg2ar (d, s)                         Example - texreg2ar r0, t1"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA1317", "texreg2gb (d, s)                         Example - texreg2gb r0, t1"
 frmMain.TV.Nodes.Add "TA1_3", tvwChild, "TA1318", "texreg2rgb (d, s)                        Example - texreg2rgb r0, t1"
 
 frmMain.TV.Nodes.Add "Texture_Address", tvwChild, "TA1_4", "PS Version 1.4"
 frmMain.TV.Nodes.Add "TA1_4", tvwChild, "TA141EX1", "d = Destination"
 frmMain.TV.Nodes.Add "TA1_4", tvwChild, "TA141EX2", "s = Source"
 frmMain.TV.Nodes.Add "TA1_4", tvwChild, "TA141", "texcrd (d, s)                            Example - texcrd t0, t1"
 frmMain.TV.Nodes.Add "TA1_4", tvwChild, "TA142", "texdepth (d)                             Example - texdepth t0"
 frmMain.TV.Nodes.Add "TA1_4", tvwChild, "TA143", "texkill (s)                              Example - texkill t0"
 frmMain.TV.Nodes.Add "TA1_4", tvwChild, "TA144", "texld (d, s)                             Example - texld t0, t1"
 DoEvents
 
 'Arithmetic Instructions
 frmMain.TV.Nodes.Add , , "Arithmetic", "Arithmetic Instructions"
 frmMain.TV.Nodes.Add "Arithmetic", tvwChild, "AIEX1", "d = Destination"
 frmMain.TV.Nodes.Add "Arithmetic", tvwChild, "AIEX2", "s = Source"
 frmMain.TV.Nodes.Add "Arithmetic", tvwChild, "AI0", "add d, s1, s2                         Example - add r0, r0, r1"
 frmMain.TV.Nodes.Add "Arithmetic", tvwChild, "AI1", "bem d, s1, s2                         Example - bem r2, r1, r3"
 frmMain.TV.Nodes.Add "Arithmetic", tvwChild, "AI2", "cmp d, s1, s2, s3                     Example - cmp r0, r1, c1, c2"
 frmMain.TV.Nodes.Add "Arithmetic", tvwChild, "AI3", "cnd d, s1, s2, s3                     Example - cnd r0, r1, r2, r3"
 frmMain.TV.Nodes.Add "Arithmetic", tvwChild, "AI4", "dp3 d, s1, s2                         Example - dp3 r0, t1, t2"
 frmMain.TV.Nodes.Add "Arithmetic", tvwChild, "AI5", "lrp d, s1, s2, s3                     Example - lrp r0, c0, r1, t0"
 frmMain.TV.Nodes.Add "Arithmetic", tvwChild, "AI6", "mad d, s1, s2, s3                     Example - mad r0, t0, t1, v1"
 frmMain.TV.Nodes.Add "Arithmetic", tvwChild, "AI7", "mov d, s                              Example - mov r0, t0"
 frmMain.TV.Nodes.Add "Arithmetic", tvwChild, "AI8", "mul d, s1, s2                         Example - mul r0, t0, t1"
 frmMain.TV.Nodes.Add "Arithmetic", tvwChild, "AI9", "sub d, s1, s2                         Example - sub r0, t0, t1"
 DoEvents
 
 'Modifiers Instructions
 frmMain.TV.Nodes.Add , , "Modifiers", "Modifiers Instructions"
 frmMain.TV.Nodes.Add "Modifiers", tvwChild, "M1_1", "PS Version 1.1 - 1.3"
 frmMain.TV.Nodes.Add "M1_1", tvwChild, "IM1_10", "Source(.b)                               Example - c0.b"
 frmMain.TV.Nodes.Add "M1_1", tvwChild, "IM1_11", "Source(.a)                               Example - c0.a"
 frmMain.TV.Nodes.Add "M1_1", tvwChild, "IM1_12", "bias                                     Example - t0_bias"
 frmMain.TV.Nodes.Add "M1_1", tvwChild, "IM1_13", "Invert                                   Example - 1-r0"
 frmMain.TV.Nodes.Add "M1_1", tvwChild, "IM1_14", "Negate                                   Example - -r0"
 frmMain.TV.Nodes.Add "M1_1", tvwChild, "IM1_15", "Signed Scale                             Example - r0_bx2"
 frmMain.TV.Nodes.Add "M1_1", tvwChild, "IM1_16", "Multiply * 2 (_x2)                       Example - add_x2"
 frmMain.TV.Nodes.Add "M1_1", tvwChild, "IM1_17", "Multiply * 4 (_x4)                       Example - add_x4"
 frmMain.TV.Nodes.Add "M1_1", tvwChild, "IM1_18", "Divide / 2 (_d2)                         Example - add_d2"
 frmMain.TV.Nodes.Add "M1_1", tvwChild, "IM1_19", "Saturate (_sat)                          Example - add_sat"
 
 frmMain.TV.Nodes.Add "Modifiers", tvwChild, "M1_4", "PS Version 1.4"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_40", "Source(.r)                               Example - c0.r"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_41", "Source(.g)                               Example - c0.g"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_42", "Source(.b)                               Example - c0.b"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_43", "Source(.a)                               Example - c0.a"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_44", "bias                                     Example - t0_bias"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_45", "Invert                                   Example - 1-r0"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_46", "Negate                                   Example - -r0"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_47", "Scale x2                                 Example - r0_x2"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_48", "Signed Scale                             Example - r0_bx2"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_49", "Multiply * 2 (_x2)                       Example - add_x2"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_401", "Multiply * 4 (_x4)                       Example - add_x4"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_402", "Multiply * 8 (_x8)                       Example - add_x8"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_403", "Divide / 2 (_d2)                         Example - add_d2"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_404", "Divide / 4 (_d4)                         Example - add_d4"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_405", "Divide / 8 (_d8)                         Example - add_d8"
 frmMain.TV.Nodes.Add "M1_4", tvwChild, "IM1_406", "Saturate (_sat)                          Example - add_sat"
 
 DoEvents
 
End Sub
